---
apiVersion: v2
appVersion: 2.8.1
description: webhook-receiver monitors IRC announce channels to get releases as soon as they are available with good filtering
name: webhook-receiver
version: 0.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - webhook-receiver
  - torrrent
home: https://github.com/geek-cookbook/charts/tree/master/charts/stable/webhook-receiver
icon: https://avatars.githubusercontent.com/u/88781313?s=200&v=4
sources:
  - https://github.com/webhook-receiver/webhook-receiver
  - https://github.com/geek-cookbook/container-images
maintainers:
  - name: funkypenguin
    email: davidy@funkypenguin.co.nz
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Updated appVersion to v1.10.0
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
