#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/geek-cookbook/webhook-receiver
  # @default -- chart.appVersion
  tag: 
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://docs.geek-cookbook.com/our-container-images/configuration/) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# See https://raw.githubusercontent.com/webhook-receiver/webhook-receiver/develop/config.toml
config: |
  id: date 
  execute-command: /usr/bin/date
  response-message: Online
  include-command-output-in-response: true


# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 9000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
