{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "webhook-receiver.harcodedValues" -}}
persistence:
  webhook-receiver-config:
    enabled: true
    mountPath: "/etc/webhooks/hooks.yaml"
    subPath: "hooks.yaml"
    type: "custom"
    volumeSpec:
      configMap:
        name: {{ include "common.names.fullname" . }}-config
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "webhook-receiver.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
